### ISSUE TITLE
Performant crashing after installing roadrunner

### ISSUE THREAD

**Issue by ComradeCaro** [MaxNeedsSnacks/roadrunner#16]
### Reproduction Steps
use a 1.16.5 forge server and install performant and roadrunner and it will crash

1. roadrunner worked fine until i installed performant and the other way around
2. when i try and run them together it crashes

### Crash Report File
2021-10-15 17:41:30,478 main WARN Advanced terminal features are not available in this environment
[17:41:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.0, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[17:41:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_302 by Temurin
[17:41:30] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17:41:30] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Julian/Desktop/Civacraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[17:41:31] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[17:41:31] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
[17:41:31] [main/INFO] [RoadRunner Early Loading/]: Loaded rule configuration file for RoadRunner: 81 options available, 0 override(s) found
[17:41:31] [main/INFO] [co.pe.co.Performant/]: Performant configs loaded
[17:41:32] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[17:41:32] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[17:41:32] [main/INFO] [co.pe.co.Performant/]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[17:41:32] [main/FATAL] [mixin/]: Mixin apply failed roadrunner.mixins.json:gen.features.StructureFeatureMixin -> net.minecraft.world.gen.feature.structure.Structure: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/gen/feature/structure/Structure::biomeConditionalGetChunk with priority 1000 cannot inject into net/minecraft/world/gen/feature/structure/Structure::func_236388_a_(Lnet/minecraft/world/IWorldReader;Lnet/minecraft/world/gen/feature/structure/StructureManager;Lnet/minecraft/util/math/BlockPos;IZJLnet/minecraft/world/gen/settings/StructureSeparationSettings;)Lnet/minecraft/util/math/BlockPos; merged by com.performant.coremod.mixin.world.StructureMixin with priority 1000 [PREINJECT Applicator Phase -> roadrunner.mixins.json:gen.features.StructureFeatureMixin -> Prepare Injections ->  -> redirect$zea000$biomeConditionalGetChunk(Lnet/minecraft/world/IWorldReader;IILnet/minecraft/world/chunk/ChunkStatus;)Lnet/minecraft/world/chunk/IChunk; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/gen/feature/structure/Structure::biomeConditionalGetChunk with priority 1000 cannot inject into net/minecraft/world/gen/feature/structure/Structure::func_236388_a_(Lnet/minecraft/world/IWorldReader;Lnet/minecraft/world/gen/feature/structure/StructureManager;Lnet/minecraft/util/math/BlockPos;IZJLnet/minecraft/world/gen/settings/StructureSeparationSettings;)Lnet/minecraft/util/math/BlockPos; merged by com.performant.coremod.mixin.world.StructureMixin with priority 1000 [PREINJECT Applicator Phase -> roadrunner.mixins.json:gen.features.StructureFeatureMixin -> Prepare Injections ->  -> redirect$zea000$biomeConditionalGetChunk(Lnet/minecraft/world/IWorldReader;IILnet/minecraft/world/chunk/ChunkStatus;)Lnet/minecraft/world/chunk/IChunk; -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_302] {}
        at net.minecraftforge.registries.GameData.init(GameData.java:178) ~[forge:?] {re:classloading}
        at net.minecraftforge.registries.GameData.<clinit>(GameData.java:132) ~[forge:?] {re:classloading}
        at net.minecraft.util.registry.Registry.forge(Registry.java:347) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Registry.forge(Registry.java:331) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:92) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}
Exception in thread "main" [17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at java.lang.reflect.Method.invoke(Method.java:498)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]:       ... 7 more
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraftforge.registries.GameData.init(GameData.java:178)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraftforge.registries.GameData.<clinit>(GameData.java:132)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.Registry.forge(Registry.java:347)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.Registry.forge(Registry.java:331)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    at net.minecraft.server.Main.main(Main.java:92)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]:    ... 13 more
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [roadrunner.mixins.json:gen.features.StructureFeatureMixin] from phase [DEFAULT] in config [roadrunner.mixins.json] FAILED during APPLY
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]:    ... 30 more
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/gen/feature/structure/Structure::biomeConditionalGetChunk with priority 1000 cannot inject into net/minecraft/world/gen/feature/structure/Structure::func_236388_a_(Lnet/minecraft/world/IWorldReader;Lnet/minecraft/world/gen/feature/structure/StructureManager;Lnet/minecraft/util/math/BlockPos;IZJLnet/minecraft/world/gen/settings/StructureSeparationSettings;)Lnet/minecraft/util/math/BlockPos; merged by com.performant.coremod.mixin.world.StructureMixin with priority 1000 [PREINJECT Applicator Phase -> roadrunner.mixins.json:gen.features.StructureFeatureMixin -> Prepare Injections ->  -> redirect$zea000$biomeConditionalGetChunk(Lnet/minecraft/world/IWorldReader;IILnet/minecraft/world/chunk/ChunkStatus;)Lnet/minecraft/world/chunk/IChunk; -> Prepare]
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[17:41:32] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]:    ... 30 more

C:\Users\Julian\Desktop\Civacraft>pause
Press any key to continue . . .

### Additional Information
i used aptweaks and randompatches with it but dont seem to make and impact it is only when the 2 mods are installed at the same time

**Comment by MaxNeedsSnacks** [comment]
#10 (https://github.com/MaxNeedsSnacks/roadrunner/issues/2#issuecomment-934590788), Performant is not compatible with RoadRunner
