### ISSUE TITLE
[1.16.5] Incompatibility with Oh the Biomes You'll Go Nether generators

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#55]
### Expected Behavior
The game should not crash whilst generating chunks whilst BYG has control of generation shapes.  I should also be able to work around this using a mixin rule disable (any hints please?)

### Actual Behavior
The game crashes immediately when attempting to generate even one chunk in the Nether.

### Reproduction Steps

1. Install Roadrunner
2. Install byg.
3. Create a new world
4. Try to enter the nether.

### Attachments
[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7855661/latest.log)

```
        net.minecraft.crash.ReportedException: Exception generating new chunk
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$21130/1542653972.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.RuntimeException
	at corgiaoc.byg.common.world.dimension.layers.WeightedMasterLayer$$Lambda$22835/1053840115.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at corgiaoc.byg.common.world.dimension.layers.WeightedMasterLayer.getRandomBiome(WeightedMasterLayer.java:27) ~[?:1.3.5]
	at corgiaoc.byg.common.world.dimension.layers.WeightedMasterLayer.func_215735_a(WeightedMasterLayer.java:23) ~[?:1.3.5]
	at me.jellysquid.mods.lithium.common.world.layer.CachedLocalLayerFactory.lambda$createInit$0(CachedLocalLayerFactory.java:16) ~[?:1.4.0]
	at me.jellysquid.mods.lithium.common.world.layer.CachedLocalLayerFactory$$Lambda$19718/1837358569.apply(Unknown Source) ~[?:?]
	at me.jellysquid.mods.lithium.common.world.layer.FastCachingLayerSampler.func_202678_a(FastCachingLayerSampler.java:49) ~[?:1.4.0]
	at net.minecraft.world.gen.layer.ZoomLayer.func_215728_a(SourceFile:530) ~[?:?]```

note that it spams the "zoom layer" and lithium references a couple times

**Comment by NighthowlerStudios** [comment]
I have looked and understood that this may or may not be a duplicate of a previous issue.  However I will do some testing just to be sure.

**Comment by NighthowlerStudios** [comment]
the issue happens regardless if byg has control of generation or not.  testing now with a rule of roadrunner to disable `mixin.gen.fast_layer_sampling`

**Comment by NighthowlerStudios** [comment]
rule set did not work.  trying without roadrunner at all

**Comment by NighthowlerStudios** [comment]
huh.  okay.  false alarm. duplicate of issue.
